In [37]:
import pandas as pd

In [38]:
law_df = pd.read_csv('../Data/Local_Law_Enforcement_Locations_4678158797704337440.csv')

In [39]:
law_df.head()

,OBJECTID,ID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,TELEPHONE,TYPE,...,TRIBAL,NUMPRE,NUMFIXSUB,NUMMOBILE,FTSWORN,FTCIV,PTSWORN,PTCIV,x,y
0,1,1004101,HIRAM POLICE DEPARTMENT,217 MAIN STREET,HIRAM,GA,30141,3249,(770) 943-3726,LOCAL POLICE DEPARTMENT,...,0,0,0,0,15,2,0,0,-9.435540e+06,4.012135e+06
1,2,1004058,GLENNVILLE POLICE DEPARTMENT,201 SOUTH CHURCH STREET,GLENNVILLE,GA,30427,1509,(912) 654-2103,LOCAL POLICE DEPARTMENT,...,0,0,0,0,8,5,3,2,-9.120461e+06,3.754819e+06
2,3,1008255,SIMMESPORT POLICE DEPARTMENT,372 MISSION DRIVE,SIMMESPORT,LA,71369,2000,(318) 941-2576,LOCAL POLICE DEPARTMENT,...,0,0,0,0,7,0,3,0,-1.022031e+07,3.630996e+06
3,4,1007969,DUBBERLY POLICE DEPARTMENT,1748 BRUSHWOOD DRIVE,DUBBERLY,LA,71024,2578,(318) 371-1020,LOCAL POLICE DEPARTMENT,...,0,0,0,0,1,0,0,0,-1.037930e+07,3.834564e+06
4,5,1009889,SEBEWAING POLICE DEPARTMENT,125 WEST MAIN STREET,SEBEWAING,MI,48759,1326,(989) 883-2380,LOCAL POLICE DEPARTMENT,...,0,0,0,0,3,0,14,0,-9.289976e+06,5.424068e+06

In [40]:
law_df.columns

Index(['OBJECTID', 'ID', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'ZIP4',
       'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY', 'COUNTYFIPS',
       'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE', 'NAICS_DESC',
       'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE', 'WEBSITE', 'CI_ID',
       'CSLLEA08ID', 'SUBTYPE1', 'SUBTYPE2', 'TRIBAL', 'NUMPRE', 'NUMFIXSUB',
       'NUMMOBILE', 'FTSWORN', 'FTCIV', 'PTSWORN', 'PTCIV', 'x', 'y'],
      dtype='object')

In [41]:
law_df.shape

(23486, 38)

In [42]:
final_df = law_df[['ID', 'NAME', 'ADDRESS', 'CITY', 'COUNTYFIPS', 'TYPE']]

In [43]:
final_df.columns = ['local_law_id', 'name', 'address', 'city_name', 'fips_code','type_of_law_enforcement']

In [44]:
final_df.head()

,local_law_id,name,address,city_name,fips_code,type_of_law_enforcement
0,1004101,HIRAM POLICE DEPARTMENT,217 MAIN STREET,HIRAM,13223,LOCAL POLICE DEPARTMENT
1,1004058,GLENNVILLE POLICE DEPARTMENT,201 SOUTH CHURCH STREET,GLENNVILLE,13267,LOCAL POLICE DEPARTMENT
2,1008255,SIMMESPORT POLICE DEPARTMENT,372 MISSION DRIVE,SIMMESPORT,22009,LOCAL POLICE DEPARTMENT
3,1007969,DUBBERLY POLICE DEPARTMENT,1748 BRUSHWOOD DRIVE,DUBBERLY,22119,LOCAL POLICE DEPARTMENT
4,1009889,SEBEWAING POLICE DEPARTMENT,125 WEST MAIN STREET,SEBEWAING,26063,LOCAL POLICE DEPARTMENT

In [45]:
city_df = pd.read_csv('../Cleaned Data/cleaned_us_cities.csv')
county_df = pd.read_csv('../Cleaned Data/cleaned_us_counties.csv')

In [46]:
merged_df = final_df.merge(county_df, left_on='fips_code', right_on='fips_code', how='inner')

In [47]:
merged_df.shape

(23252, 10)

In [49]:
merged_df.head()

,local_law_id,name,address,city_name,fips_code,type_of_law_enforcement,Unnamed: 0,state_id,county_name,state_name
0,1004101,HIRAM POLICE DEPARTMENT,217 MAIN STREET,hiram,13223,LOCAL POLICE DEPARTMENT,3062,GA,Paulding,Georgia
1,1004058,GLENNVILLE POLICE DEPARTMENT,201 SOUTH CHURCH STREET,glennville,13267,LOCAL POLICE DEPARTMENT,6398,GA,Tattnall,Georgia
2,1008255,SIMMESPORT POLICE DEPARTMENT,372 MISSION DRIVE,simmesport,22009,LOCAL POLICE DEPARTMENT,6548,LA,Avoyelles,Louisiana
3,1007969,DUBBERLY POLICE DEPARTMENT,1748 BRUSHWOOD DRIVE,dubberly,22119,LOCAL POLICE DEPARTMENT,3549,LA,Webster,Louisiana
4,1009889,SEBEWAING POLICE DEPARTMENT,125 WEST MAIN STREET,sebewaing,26063,LOCAL POLICE DEPARTMENT,8824,MI,Huron,Michigan

In [48]:
city_df['city_name'] = city_df['city_name'].str.lower()
merged_df['city_name'] = merged_df['city_name'].str.lower()

In [50]:
merged_df_final = merged_df.merge(city_df, how='inner', on=['fips_code', 'city_name'])

In [51]:
merged_df_final.shape

(20666, 12)

In [53]:
merged_df_final = merged_df_final[['local_law_id', 'name', 'address', 'type_of_law_enforcement']]

In [54]:
merged_df_final.head()

,local_law_id,name,address,type_of_law_enforcement
0,1004101,HIRAM POLICE DEPARTMENT,217 MAIN STREET,LOCAL POLICE DEPARTMENT
1,1004058,GLENNVILLE POLICE DEPARTMENT,201 SOUTH CHURCH STREET,LOCAL POLICE DEPARTMENT
2,1008255,SIMMESPORT POLICE DEPARTMENT,372 MISSION DRIVE,LOCAL POLICE DEPARTMENT
3,1007969,DUBBERLY POLICE DEPARTMENT,1748 BRUSHWOOD DRIVE,LOCAL POLICE DEPARTMENT
4,1009889,SEBEWAING POLICE DEPARTMENT,125 WEST MAIN STREET,LOCAL POLICE DEPARTMENT

In [55]:
merged_df_final.to_csv('../Cleaned Data/cleaned_law_enforcement.csv', index=False)